version: '3'
services:
  app:
    container_name: mongoDB_arb
    restart: always
    build: .
    volumes: 
      - ".:/app/"
    command: 
      nodemon index.js
    ports:
      - '80:3000'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
